"""Load the bundled RISC-V ISA reference data.

The JSON under ``data/riscv/`` is generated by ``scripts/gen_riscv_data.py``
(self-contained, no network). This module reads it into light dataclasses for
the OpenSearch write path (``backends/opensearch_docs.riscv_actions``). Like the
rest of xevdb's parsers it is dependency-free — no ``opensearch-py`` here.
"""
from __future__ import annotations

import json
from dataclasses import dataclass
from importlib import resources
from pathlib import Path
from typing import Any

#: logical categories <-> their JSON file / list key.
CATEGORIES: tuple[str, ...] = (
    "instructions", "registers", "csrs", "extensions", "pseudo",
)


@dataclass
class Instruction:
    id: str
    name: str
    mnemonic: str
    extension: str
    format: str
    width: int
    mask: str
    match: str
    operands: str
    syntax: str
    description: str
    pseudo: bool


@dataclass
class Register:
    id: str
    name: str
    abi: str
    number: int
    group: str
    role: str
    saver: str


@dataclass
class Csr:
    id: str
    addr: str
    name: str
    privilege: str
    access: str
    description: str


@dataclass
class Extension:
    id: str
    letter: str
    name: str
    version: str
    description: str


@dataclass
class Pseudo:
    id: str
    name: str
    expansion: str
    base: str
    description: str


@dataclass
class RiscvData:
    """Everything ingested for one RISC-V reference build."""
    spec_version: str
    instructions: list[Instruction]
    registers: list[Register]
    csrs: list[Csr]
    extensions: list[Extension]
    pseudo: list[Pseudo]

    def counts(self) -> dict[str, int]:
        return {
            "instructions": len(self.instructions),
            "registers": len(self.registers),
            "csrs": len(self.csrs),
            "extensions": len(self.extensions),
            "pseudo": len(self.pseudo),
        }


_CTOR = {
    "instructions": Instruction,
    "registers": Register,
    "csrs": Csr,
    "extensions": Extension,
    "pseudo": Pseudo,
}


def _read_category(data_dir: Path | None, category: str) -> tuple[str, list[dict]]:
    """Return (spec_version, rows) for one category JSON file."""
    if data_dir is not None:
        text = (Path(data_dir) / f"{category}.json").read_text(encoding="utf-8")
    else:
        text = (resources.files("xevdb")
                .joinpath("data", "riscv", f"{category}.json")
                .read_text(encoding="utf-8"))
    obj: dict[str, Any] = json.loads(text)
    return obj.get("spec_version", ""), obj.get(category, [])


def load(data_dir: str | Path | None = None) -> RiscvData:
    """Load the RISC-V reference data, from a directory or the bundled package."""
    ddir = Path(data_dir) if data_dir is not None else None
    spec_version = ""
    kw: dict[str, list[Any]] = {}
    for category in CATEGORIES:
        version, rows = _read_category(ddir, category)
        spec_version = spec_version or version
        ctor = _CTOR[category]
        kw[category] = [ctor(**row) for row in rows]
    return RiscvData(spec_version=spec_version, **kw)
